server:
  port : 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmarker
    username: root
    password: abc123
  jpa:
    open-in-view: false
    hibernate:
#      ddl-auto: create